apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: stats
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '6.0.x'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-repo
      interval: 1m
  values:
    replicaCount: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi
