apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: stats
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '6.0.x'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-repo
      interval: 1m
  values:
    replicaCount: 2
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 32Mi
