apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  releaseName: redis
  chart:
    spec:
      chart: redis
      version: "15.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-repo
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    usePassword: false
    cluster:
      enabled: false
    master:
      persistence:
        enabled: false
