apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
namespace: podinfo
metadata:
  name: podinfo
spec:
  test:
    enable: true
  values:
    ingress:
      hosts:
        - host: podinfo.dev.local
