apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
namespace: redis
metadata:
  name: redis
spec:
  values:
    usePassword: false
    cluster:
      enabled: false
    master:
      persistence:
        enabled: false
